"""
This script implements the RAG pipeline to answer user queries 
about movies based on context retrieved from the Chroma vector database.
This script will serve as the foundation of the movie_rag_app Streamlit app.

Ensure all dependencies are installed by running:
  pip install -r requirements.txt

Pipeline Overview:
------------------
The pipeline includes the following key components:

1. Loading Dependencies:
   - ChromaDB: Stores and queries embedded documents.
   - SentenceTransformers: Generates embeddings for queries and documents.
   - Hugging Face Transformers: Utilized for loading and using a language model (Mistral-7B-Instruct-v0.3 in this script).

2. Main Functions:
   - Functions to load models and tokenizers, generate query embeddings, retrieve documents from ChromaDB, 
     and generate answers from the LLM.

Usage:
------
To run the pipeline:
1. Ensure that ChromaDB is properly set up with embedded movie chunks.
2. Modify the path to the ChromaDB collection in the `load_chromadb` function.
3. Execute the script and test the queries.

Test Queries:
-------------
Here are some sample test queries to validate the pipeline's functionality:
1. What is a good movie about a road trip gone wrong?
2. What is the plot of The Hunger Games?
3. Who are the main characters of The Incredibles?

Notes:
------
- This pipeline is designed for GPU inference using Mistral-7B with 4-bit quantization.
- Ensure that PyTorch is installed with CUDA support (torch version compiled with CUDA).
- Use a CUDA-enabled NVIDIA GPU with sufficient VRAM (e.g., T4, V100, A100).
"""


# Import dependencies
import chromadb # Vector Store
from sentence_transformers import SentenceTransformer # Embedding model
import torch # LLM
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig # LLM
import textwrap # Answer generation

# Functions to load dependencies
def load_chromadb(file_path, collection_name):
    """
    Loads and initializes Chroma DB collection.

    Parameters
    ----------
    file_path: str
        Path of the chroma db file.
    collection_name: str
        Name of the collection to load.
    
    Returns
    -------
    object
        Chroma DB client collection fully loaded.
    """
    client = chromadb.PersistentClient(path=file_path) # Whatever your path is for chroma_db
    return client.get_collection(name=collection_name) # Collection to return

def load_embedding_model(model_name):
    """
    Loads a embedding model from sentence transformers.
    Has to be the same model used on the documents.
    Used to embed user queries in the rap pipeline. 

    Parameters
    ----------
    model_name: str
        Name of the model to load from sentence transformers.
    
    Returns
    -------
    object
        A preloaded SentenceTransformer model.
    """
    return SentenceTransformer(model_name)

def load_llm_and_tokenizer(model_id):
    """
    Load a language model and its corresponding tokenizer.

    Parameters
    ----------
    model_id : str
        Hugging Face model ID used to initialize the tokenizer
        and language model.

    Returns
    -------
    tuple
        A tuple containing:
        - tokenizer : AutoTokenizer
        - model : AutoModelForCausalLM
    """
    # Define the 4-bit configuration
    quant_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
    )

    tokenizer = AutoTokenizer.from_pretrained(model_id)

    # Loading model in 4-bit to fit Mistral-7B in T4 memory
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=quant_config,
        device_map="auto",
    )
    return tokenizer, model

# Define functions for RAG pipeline
def get_query_embedding(query, embedding_model):
  """
    This function takes a input query removes leading and
    lagging whitespaces, then generates an embedding for the query.

    The resulting embedding is converted to a Python list format, making it
    compatible with vector databases such as Chroma.

    Parameters
    ----------
    query: str
        The input query string to be embedded.

    Returns
    --------
    list
        The embedding generated by the embedding model.
        Converted to a list as expected by chroma db.
    """
  return embedding_model.encode(query.strip()).tolist()

def retrieve_documents(query, collection, embedding_model, top_k=5):
    """
    This function takes an input query, generates its embedding,
    and uses that embedding to retrieve the top-k most relevant
    document chunks from a Chroma collection.

    It returns the retrieved documents sorted by their IDs.

    Parameters
    ----------
    query : str
        The input query string used for retrieval.
    collection : object
        The Chroma collection containing embedded document chunks.
    embedding_model : object
        A preloaded SentenceTransformer model used to generate the query embedding.
    top_k : int, optional
        The number of top matching document chunks to retrieve, the default is 5.

    Returns
    -------
    sorted_documents: list
        The list of the retrieved documents sorted by their IDs.
    """
    # Call query embedding function
    query_embedding = get_query_embedding(query, embedding_model)

    # Query chroma db
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=["documents"]
    )
    # Return docs and ids
    paired_sorted = sorted(zip(results['ids'][0], results['documents'][0]), key=lambda x: int(x[0].split('_')[-1]))
    sorted_ids, sorted_documents = zip(*paired_sorted) # Unzip the pair
    return sorted_documents

def generate_answer(query, context, model, tokenizer):
    """
    Concatenates relevant movie chunks and asks Mistral to answer the query based on them.

    Parameters
    ----------
    query: str
        The users questions.
    context: list
        The documents retrieved from the ChromaDB.
    model: object
        LLM used to generate the answer to the users query based off the retrived context.
    tokenizer: object
        Tokenizer used for the LLM.
    
    Returns
    -------
    answer_only: str
        The answer generated by the LLM using the retrieved context.
    """
    # Combine the retrieved docs into a single text block
    context_block = "\n\n".join(context)

    # Create the prompt using Mistral's specific instruction format
    prompt = f"""<s>[INST] You are an expert movie assistant. Use the following context to answer the question.
    If you don't know the answer based on the context, just say you don't know. Do not spoil any movies that you mention.

    Context:
    {context_block}

    Question: {query}
    [/INST]"""

    # Convert prompt to tokens and send to GPU 
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    # Generate the answer
    outputs = model.generate(
        **inputs,
        max_new_tokens=300,
        temperature=0.7,          # Temperature is set to 0.7, seems to be decent
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id
    )


    # Calculate the exact length of the input prompt
    input_length = inputs['input_ids'].size(1)

    # Slice the output tensor to ignore the prompt, then decode only the new tokens
    answer_only = tokenizer.decode(outputs[0][input_length:], skip_special_tokens=True)

    return answer_only.strip()

def rag_pipeline(query, collection, embedding_model, model, tokenizer, top_k = 3):
  """
  Retrieve the relevant movies based on the query and send that to the model for an answer.

  Parameters
  ----------
  query : str
    The input query string used for retrieval.
  collection : object
    The Chroma collection containing embedded document chunks.
  embedding_model : object
    A preloaded SentenceTransformer model used to generate the query embedding.
  model: object
    LLM used to generate the answer to the users query based off the retrived context.
  tokenizer: object
    Tokenizer used for the LLM.
  top_k : int, optional
    The number of top matching document chunks to retrieve, the default is 5.
  
  Returns
  -------
  answer: str
    The answer generated by the LLM using the retrived context. 
  """

  # Retrieve the context documents
  context = retrieve_documents(query, collection, embedding_model, top_k = top_k)
  
  # Generate the answer with the retrieved context
  answer = generate_answer(query, context, model, tokenizer)

  return answer

# Test Cases
def main():
   # Load dependices
   collection = load_chromadb(r"C:\Users\KRAyu\OneDrive\nlp_essentials\course_project\MovieSummaries\chroma_db\chroma_db", "movie_chunks")
   embedding_model = load_embedding_model("all-mpnet-base-v2")
   tokenizer, model = load_llm_and_tokenizer("mistralai/Mistral-7B-Instruct-v0.3")


   # Test case 1.
   query = "What is a good movie about a road trip gone wrong?"
   answer = rag_pipeline(query, collection, embedding_model, model, tokenizer, top_k = 5)
   print(textwrap.fill(answer, width=80))   
   print()

   # Test case 2.
   query = "What is the plot of The Hunger Games?"
   answer = rag_pipeline(query, collection, embedding_model, model, tokenizer, top_k = 5)
   print(textwrap.fill(answer, width=80))
   print()

   # Test case 3.
   query = "Who are the main characters of The Incredibles?"
   answer = rag_pipeline(query, collection, embedding_model, model, tokenizer, top_k = 5)
   print(textwrap.fill(answer, width=80))

if __name__ == '__main__':
    main()